# Generated by Django 6.0.7 on 2026-07-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('post_slug', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Page view',
                'verbose_name_plural': 'Page views',
                'ordering': ['-created_at'],
            },
        ),
    ]
