# Generated by Django 6.0.7 on 2026-07-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_pt', models.CharField(blank=True, max_length=200)),
                ('content_en', models.TextField(blank=True)),
                ('content_pt', models.TextField(blank=True)),
                ('meta_description_en', models.CharField(blank=True, max_length=300)),
                ('meta_description_pt', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['slug'],
            },
        ),
    ]
