# Generated by Django 6.0.7 on 2026-07-25 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_platform_features'),
        ('content_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(blank=True, help_text='Tópico usado na geração IA (ex: "top kubectl commands")', max_length=255)),
                ('post_type', models.CharField(choices=[('cheatsheet', 'Cheatsheet'), ('tip', 'Tip'), ('comparison', 'Comparison')], default='cheatsheet', max_length=20)),
                ('slides', models.JSONField(blank=True, default=list)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('cover_svg', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('published', 'Published')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_carousels', to='blog.post')),
            ],
            options={
                'verbose_name': 'Instagram carousel',
                'verbose_name_plural': 'Instagram carousels',
                'ordering': ['-updated_at'],
            },
        ),
    ]
