# Generated by Django 6.0.7 on 2026-07-25 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_platform_features'),
        ('content_pipeline', '0002_instagram_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramcarousel',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Carrossel Instagram', 'verbose_name_plural': 'Carrosséis Instagram'},
        ),
        migrations.AlterField(
            model_name='instagramcarousel',
            name='source_post',
            field=models.ForeignKey(blank=True, help_text='Se escolher um post, use "Gerar a partir do post" em vez do tópico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_carousels', to='blog.post', verbose_name='Post do blog (opcional)'),
        ),
        migrations.AlterField(
            model_name='instagramcarousel',
            name='title',
            field=models.CharField(blank=True, help_text='Opcional — se vazio, usa o tópico.', max_length=255),
        ),
        migrations.AlterField(
            model_name='instagramcarousel',
            name='topic',
            field=models.CharField(blank=True, help_text='Ex: "5 comandos kubectl essenciais" — usado pela IA para criar os slides.', max_length=255, verbose_name='Tópico'),
        ),
    ]
