# Generated by Django 6.0.7 on 2026-07-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='body_markdown',
            field=models.TextField(blank=True, help_text='Weekly curation draft (PT-BR markdown)'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='discord_channel_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='discord_message_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='body_html_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newslettercampaign',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending review'), ('draft', 'Draft'), ('scheduled', 'Scheduled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=16),
        ),
    ]
