# Generated by Django 6.0.7 on 2026-07-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadMagnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_pt', models.CharField(blank=True, max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_pt', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='lead-magnets/')),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead magnet',
                'verbose_name_plural': 'Lead magnets',
                'ordering': ['slug'],
            },
        ),
    ]
