# Generated by Django 6.0.7 on 2026-07-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='content_teaching',
            field=models.TextField(blank=True, help_text='Content & Teaching section text'),
        ),
        migrations.AddField(
            model_name='author',
            name='goals',
            field=models.TextField(blank=True, help_text='Current Goals - one per line'),
        ),
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
