# Generated by Django 6.0.7 on 2026-07-24 14:08

from django.db import migrations, models


def seed_profile_links(apps, schema_editor):
    ProfileLink = apps.get_model('blog', 'ProfileLink')
    if ProfileLink.objects.exists():
        return

    cards = [
        {
            'section': 'card',
            'order': 1,
            'title_en': 'YouTube Channel',
            'title_pt': 'Canal no YouTube',
            'description_en': 'Videos about DevOps, Kubernetes and Homelab',
            'description_pt': 'Vídeos sobre DevOps, Kubernetes e Homelab',
            'url': 'https://youtube.com/@matheusthurler',
            'external': True,
            'image': 'images/icons/youtube.png',
        },
        {
            'section': 'card',
            'order': 2,
            'title_en': 'Blog',
            'title_pt': 'Blog',
            'description_en': 'Technical articles about technology',
            'description_pt': 'Artigos técnicos sobre tecnologia',
            'internal_route': 'blog:home',
            'external': False,
            'icon': 'posts',
        },
        {
            'section': 'card',
            'order': 3,
            'title_en': 'LinkedIn',
            'title_pt': 'LinkedIn',
            'description_en': 'My professional profile',
            'description_pt': 'Meu perfil profissional',
            'url': 'https://linkedin.com/in/matheus-thurler',
            'external': True,
            'image': 'images/icons/linkedin.png',
        },
        {
            'section': 'card',
            'order': 4,
            'title_en': 'Instagram',
            'title_pt': 'Instagram',
            'description_en': '@maththurler.devops',
            'description_pt': '@maththurler.devops',
            'url': 'https://instagram.com/maththurler.devops',
            'external': True,
            'image': 'images/icons/instagram.png',
        },
        {
            'section': 'card',
            'order': 5,
            'title_en': 'TikTok',
            'title_pt': 'TikTok',
            'description_en': '@matheusthurler.devops',
            'description_pt': '@matheusthurler.devops',
            'url': 'https://www.tiktok.com/@matheusthurler.devops',
            'external': True,
            'image': 'images/icons/tiktok.png',
        },
        {
            'section': 'card',
            'order': 6,
            'title_en': 'GitHub',
            'title_pt': 'GitHub',
            'description_en': 'My open source projects',
            'description_pt': 'Meus projetos open source',
            'url': 'https://github.com/Matheus-Thurler',
            'external': True,
            'image': 'images/icons/github.png',
        },
        {
            'section': 'card',
            'order': 7,
            'title_en': 'Contact',
            'title_pt': 'Contato',
            'description_en': 'contato@matheusthurler.com.br',
            'description_pt': 'contato@matheusthurler.com.br',
            'url': 'mailto:contato@matheusthurler.com.br',
            'external': True,
            'image': 'images/icons/email.png',
        },
    ]
    social = [
        {
            'section': 'social',
            'order': 1,
            'title_en': 'GitHub',
            'title_pt': 'GitHub',
            'url': 'https://github.com/Matheus-Thurler',
            'external': True,
            'icon': 'github',
        },
        {
            'section': 'social',
            'order': 2,
            'title_en': 'YouTube',
            'title_pt': 'YouTube',
            'url': 'https://youtube.com/@matheusthurler',
            'external': True,
            'icon': 'youtube',
        },
        {
            'section': 'social',
            'order': 3,
            'title_en': 'LinkedIn',
            'title_pt': 'LinkedIn',
            'url': 'https://linkedin.com/in/matheus-thurler',
            'external': True,
            'icon': 'linkedin',
        },
        {
            'section': 'social',
            'order': 4,
            'title_en': 'Email',
            'title_pt': 'Email',
            'url': 'mailto:matheus@matheusthurler.com.br',
            'external': True,
            'icon': 'email',
        },
    ]

    for item in cards + social:
        ProfileLink.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('card', 'Card principal'), ('social', 'Ícone social (rodapé)')], default='card', help_text='Cards aparecem na lista; ícones sociais ficam na fileira inferior.', max_length=10)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_pt', models.CharField(blank=True, max_length=200)),
                ('description_en', models.CharField(blank=True, max_length=300)),
                ('description_pt', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, help_text='URL externa, mailto: ou caminho (/about/). Deixe vazio se usar rota interna.', max_length=500)),
                ('internal_route', models.CharField(blank=True, help_text='Nome de rota Django (ex.: blog:home). Tem prioridade sobre URL.', max_length=100)),
                ('external', models.BooleanField(default=True, help_text='Abre em nova aba quando marcado.')),
                ('image', models.CharField(blank=True, help_text='Ícone PNG em static/ (ex.: images/icons/youtube.png).', max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Ícone SVG: posts, github, youtube, linkedin, email.', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Link da página /links/',
                'verbose_name_plural': 'Links da página /links/',
                'ordering': ['section', 'order', 'pk'],
            },
        ),
        migrations.RunPython(seed_profile_links, migrations.RunPython.noop),
    ]
