# Generated by Django 6.0.7 on 2026-07-25 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profilelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_pt', models.CharField(blank=True, max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_pt', models.TextField(blank=True)),
                ('cover', models.CharField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
                'ordering': ['order', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='content_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the post content was last meaningfully updated', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='crosspost_linkedin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='crosspost_mastodon',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='crosspost_telegram',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='og_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='og_description_pt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='og_title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='og_title_pt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='show_updated_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='SeriesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_memberships', to='blog.post')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_posts', to='blog.series')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('series', 'post')},
            },
        ),
        migrations.AddField(
            model_name='series',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='series_list', through='blog.SeriesPost', to='blog.post'),
        ),
        migrations.CreateModel(
            name='PostFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.BooleanField()),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='blog.post')),
            ],
            options={
                'verbose_name': 'Post feedback',
                'verbose_name_plural': 'Post feedback',
                'unique_together': {('post', 'visitor_hash')},
            },
        ),
    ]
