# Generated by Django 6.0.7 on 2026-07-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('youtube', 'YouTube'), ('github', 'GitHub'), ('discord', 'Discord')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.TextField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
            },
        ),
    ]
